### ISSUE TITLE
Reading Pileups

### ISSUE THREAD

**Issue by Tabima** [knausb/covR#1]
Well, I came to the same conclusion than you: reading pileups is a drag.

I've been  trying 2 "fast table readers": 

`read_tsv` from [`readr`]() and `fread` from [`data.table`](http://cran.r-project.org/web/packages/data.table/index.html):

```
system('wc -l A6.pileup)
[1] 23451219
system.time(read_tsv("A6.pileup"))
   user  system elapsed 
184.059   4.004 296.237 
system.time(fread("A6.pileup"))
 user  system elapsed 
 15.713   1.344 146.580 
```

So far, I'm more inclined to read pileup files using fread. 
Do you have anything faster, or should we use fread instead?

thanks!

**Comment by knausb** [comment]
I'm exploring an option.  Will get back to you when I have it implemented.
